######################################################
################# Setup Elasticsearch ################
######################################################
---

- name: "Create directories"
  file:
    group: "{{ es_group }}"
    owner: "{{ es_user }}"
    mode: u+rw,g+rw
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ elastic_dir }}"
    - "{{ elastic_dir }}/data"
    - "{{ elastic_dir }}/config"

- name: Install Templates
  template:
    src: "templates/{{ item }}.yml.j2"
    dest: "{{ elastic_dir }}/{{ item }}.yml"
    group: "{{ es_group }}"
    owner: "{{ es_user }}"
    mode: u+rw,g+rw
  with_items:
    - es-client
    - es-curator-config
    - es-curator_v1beta1
    - es-data-pdb
    - es-data
    - es-discovery-svc
    - es-master-pdb
    - es-master
    - es-svc
    - pvc-data

- name: Install Config Templates
  template:
    src: "templates/{{ item }}.j2"
    dest: "{{ elastic_config_dir }}/{{ item }}"
    group: "{{ es_group }}"
    owner: "{{ es_user }}"
    mode: u+rw,g+rw
  with_items:
    - elasticsearch.yml
    - jvm.options
    - log4j2.properties

- name: Flush Config
  command: 'kubectl --kubeconfig="{{ kubernetes_conf_file }}" delete configmap {{ elastic_config_map }}-{{ item.0 }}'
  with_indexed_items:
    - elasticsearch.yml
    - jvm.options
    - log4j2.properties
  ignore_errors: true

- name: Create Config
  command: 'kubectl --kubeconfig="{{ kubernetes_conf_file }}" create configmap {{ elastic_config_map }}-{{ item.0 }} --from-file {{ elastic_config_dir }}/{{ item.1 }}'
  with_indexed_items:
    - elasticsearch.yml
    - jvm.options
    - log4j2.properties

- name: Flush Deployments
  shell: |
    kubectl --kubeconfig="{{ kubernetes_conf_file }}" delete -f {{ elastic_dir }}/{{ item }}.yml
    while [ $(kubectl --kubeconfig="{{ kubernetes_conf_file }}" get -f {{ elastic_dir }}/{{ item }}.yml | tail -n +2 | wc -l) != '0' ]; do
      echo -n .;
      sleep 1;
    done;
    sleep 5;
  with_items:
    - es-discovery-svc
    - es-svc
    - es-master
    - pvc-data
#    - es-client
#    - es-data
  ignore_errors: true

- name: Deploy PVC
  shell: |
    kubectl --kubeconfig="{{ kubernetes_conf_file }}" create -f {{ elastic_dir }}/pvc-data.yml
    while [ $(kubectl --kubeconfig="{{ kubernetes_conf_file }}" get -f {{ elastic_dir }}/pvc-data.yml | tail -n +2 | awk '{ print $2 }') != 'Bound' ]; do
      echo -n .;
      sleep 1;
    done;
    while [ $(kubectl --kubeconfig="{{ kubernetes_conf_file }}" get ep | grep $(kubectl --kubeconfig="{{ kubernetes_conf_file }}" get -f {{ elastic_dir }}/pvc-data.yml | tail -n +2 | awk '{ print $1 }') | wc -l) == '0' ]; do
      echo -n .;
      sleep 1;
    done;

- name: Deploy Pods
  shell: |
    kubectl --kubeconfig="{{ kubernetes_conf_file }}" create -f {{ elastic_dir }}/{{ item }}.yml
    while [ $(kubectl --kubeconfig="{{ kubernetes_conf_file }}" get -f {{ elastic_dir }}/{{ item }}.yml | tail -n +2 | awk '{ print $5}') == '0' ]; do
      echo -n .;
      sleep 1;
    done;
  with_items:
    - es-master
    #- es-client
    #- es-data

- name: Deploy Services
  command: 'kubectl --kubeconfig="{{ kubernetes_conf_file }}" create -f {{ elastic_dir }}/{{ item }}.yml'
  with_items:
    - es-discovery-svc
    - es-svc
#    - es-client
#    - es-data
