apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ moloch_pv_data }}
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ moloch_pv_size_gb }}Gi
  volumeName: {{ moloch_pv_data }}
